### PR TITLE
add specs and travis integration

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Looks like all the tests worked, it just exited with a 1 due to the deprecation.

**Comment by Arcanemagus** [comment]
Just filed this, as I've seen that before: https://github.com/AtomLinter/atom-linter/issues/54

**Comment by Arcanemagus** [comment]
@dirk-thomas looks like if we update the `atom-linter` dependency to `^3.3.3` that deprecation error should be fixed.

**Comment by dirk-thomas** [comment]
Thanks for the fast fix!

The Travis CI will always install the latest version so this (as well as future PRs) is green now. Since it doesn't make a difference for users I don't think we have to bump the version dependency.

**Pull request merged**
